### ISSUE TITLE
Can't modify tasks

### ISSUE THREAD

**Issue by dbourrion** [samgiz/vscode-kanbn#10]
Hi
Since the last update, I'm enable to modify "old" tasks or to add some tags to new tasks :(

**Comment by dbourrion** [comment]
Hi :)
Here's a Test Board I just created.
It was even impossible to create some new task :(
The "Create task" windows opens, but nothing is saved when I use the Save button

[Test.zip](https://github.com/samgiz/vscode-kanbn/files/11229210/Test.zip)

**Comment by samgiz** [comment]
So there were a few small issues that caused this that should now be fixed in 13.0.1. Let me know if you still encounter issues.

In addition I'll mention that the extension doesn't currently allow you to create two tasks with the same name, or have an empty task name, or have an empty tag. If any of the restrictions is not satisfied, there is currently no visual indication that you should edit the inputs, but the task won't save (and there won't be a popup saying that the task has saved). I believe in your test board in particular it wouldn't save because you had the task name field empty. :)

**Comment by dbourrion** [comment]
Hi
Ok, it's working again, many thx :)
