### ISSUE TITLE
Command "kanbn not found"

### ISSUE THREAD

**Issue by dbourrion** [samgiz/vscode-kanbn#5]
Hi.

When I'm trying to open a board by clicking on the icons at the botton of VSC, I'm getting a message, "kanbn not found".

That message come's even if the board is already open. Any idea of what is causing that ?

Juste one more thing : I've use the previous version of that extension, the one that was forked for the present one. It's perhaps a explanation ?

Many thanks

![Capture d’écran du 2023-03-26 14-54-29](https://user-images.githubusercontent.com/400398/227777275-d88bf1b5-45ef-411c-b5c7-2e8545aa5289.png)

**Comment by dbourrion** [comment]
Hi

Apologizes for my english

In fact I was just asking why I got this error :)

**Comment by samgiz** [comment]
Hi @dbourrion, I haven't used the bottom panel at all since I've started working on the project, so I'm not too surprised that it's broken. :) The fix should be fairly straightforward, I forgot to rename `kanbn.board` to `kanbn.openBoard` in one place. Thanks for reporting, I'll include a fix in the next release!

Out of curiosity, what would you expect the bottom panel to do? It used to open the board for the current workspace in the old extension. Now that there can be multiple boards per workspace the equivalent command will open a list of boards to choose from (same as the `Open Board` command from the command palette). Do you maybe have a better suggestion for what it should do?

**Comment by dbourrion** [comment]
Hi
Oh, cool to learn that a fix is on his way.
Yje option of opening a list of board to choose one looks perfect for me :)

**Comment by samgiz** [comment]
The fix is now live in 0.13.0.
